version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  e2e:
    docker:
      - image: circleci/node:12.16.1-browsers
        user: root

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install nginx
          command: sudo apt-get update && sudo apt-get install nginx && sudo service nginx restart
      - run:
          name: Install deps
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Copy files
          command: cp ./build/* /var/www/html/
      - run:
          name: Test
          command: npm run test:ci:e2e
      - store_artifacts:
          path: e2e/reports

workflows:
  test:
    jobs:
      - node/test:
          version: 12.16.1
      - e2e:
          requires:
            - node/test
