version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm ci
      - run: npm run test

      - save_cache:
          paths:
            - $HOME/.npm
          key: npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}

  e2e:
    docker:
      - image: circleci/node:10.16.0-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
        name: Install nginx
        command: sudo apt-get update && sudo apt-get install nginx
      - run:
          name: Install deps
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Copy files
          command: cp ./build/* /usr/share/nginx/html/
      - run:
          name: Test
          command: cd e2e && nightwatch

  automerge:
    docker:
      - image: circleci/node:10.16.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run:
          name: Merge greenkeeper branch
          command: npm run ci:automerge

workflows:
  version: 2
  test:
    jobs:
      - test
      - e2e:
        requires:
          - test
      - automerge:
          requires:
            - e2e
          filters:
            branches:
              only: /greenkeeper\S*/
